DB_FILEPATH_UNIX = '/website/database.db'
DB_FILEPATH_WINDOWS = '\\website\\database.db'
CLEANUP_COMMAND_UNIX = 'rm -rf ' + DB_FILEPATH_UNIX
CLEANUP_COMMAND_WINDOWS = 'del /f ' + DB_FILEPATH_WINDOWS
OSTYPE_LINUX = 'Linux'
OSTYPE_DARWIN = 'Darwin'
OSTYPE_WINDOWS = 'Windows'
CLEANUP_OP_SUCCESS = 'SUCCESS'
CLEANUP_OP_FAILURE = 'FAILURE'

DB_DELETION_SECRET_KEY_HASH = b"\xba\xa5\xc4'(E\x0e\xda;\xb3LW^\x9a\xd0}"
